package keys

const (
	CommandStart                    = "start"
	Register                        = "registration"
	Info                            = "help"
	CreateNewGroup                  = "createNewGroup"
	JoinTheExistGroup               = "toExistGroup"
	GoToMainMenu                    = "main_menu"
	GoToUserMenuSettings            = "GoToUserMenuSettings"
	GoToChangeLanguageMenu          = "GoToChangeLanguageMenu"
	GoToChangeUserName              = "GoToChangeUserName"
	ChatIdPrefix                    = "s4i-"
	ChatIdSuffix                    = 12345
	GoToGroupsMenu                  = "go_to_groups_menu"
	ShowAllChiefsGroups             = "ShowAllChiefsGroups"
	RenameGroupWithId               = "RenameGroupWithId-"
	ShowAllEmployeesFromGroupWithId = "ShowAllEmployeesFromGroupWithId-"
	EmployeeIDtoDeleteFromGroup     = "EmployeeIDtoDeleteFromGroup-"
	EmployeeIDtoCopyToANotherGroup  = "EmployeeIDtoCopyToANotherGroup-"
	ShowAllEmployeeGroups           = "ShowAllEmployeeGroups"
	DeleteGroup                     = "DeleteGroup-"
	CopyEmployeeGroupID             = "CopyEmployeeToGroupWithId-"
	CopyEmployeeEmployeeID          = "CopyEmployeeEmployeeID-"
	ConfirmDeletingEmployeeId       = "ConfirmDeletingEmployeeId-"
	ConfirmDeletingGroup            = "ConfirmDeletingGroup"
	LeaveGroupID                    = "LeaveGroupID-"
	ConfirmLeavingGroup             = "ConfirmLeavingGroup"
	CreateNewTaskKeyData            = "CreateNewTaskKeyData-"
	SkipDescritionEntering          = "SkipDescritionEntering"
	AddWholeGroupToTaskKeyData      = "AddWholeGroupToTaskKeyData"
	AddSomeEmployeesToTaskKeyData   = "AddSomeEmployeesToTaskKeyData"
	AssignToEmployeeWithID          = "AssignToEmployeeWithID-"
	ToSeeTaskDetailsTaskID          = "ToSeeTaskDetailsTaskID-"
	ShowAllTasksFromGroupID         = "ShowAllTasksFromGroupID-"
)
